// SPDX-License-Identifier: MIT
// Auto-generated by ESBMC 8.2.0
// Foundry coverage test reconstructed from ESBMC counterexamples.
pragma solidity >=0.8.0;

import {Test} from "forge-std/Test.sol";
import {KA} from "../src/KA.sol";

contract KACovTest is Test {
  KA c0;
  function setUp() public {
    c0 = new KA();
  }
  function test_cov_0() public {
    c0.setBig(115792089237316195423570985008687907853269984665640564039457584007913129639935);
  }
  function test_cov_1() public {
    c0.setBig(100);
  }
  function test_cov_2() public {
    c0.setHash(bytes32(0x0000000000000000000000000000000000000000000000000000000000000007));
  }
  function test_cov_3() public {
    c0.setHash(bytes32(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff));
  }
}
