// SPDX-License-Identifier: MIT
// Auto-generated by ESBMC 8.2.0
// Foundry coverage test reconstructed from ESBMC counterexamples.
pragma solidity >=0.8.0;

import {Test} from "forge-std/Test.sol";
import {KB} from "../src/KB.sol";

contract KBCovTest is Test {
  KB c0;
  function setUp() public {
    c0 = new KB(bytes4(0x00000000));
  }
  function test_cov_0() public {
    c0.poke(bytes4(0x12345678));
  }
  function test_cov_1() public {
    c0.poke(bytes4(0xffffffff));
  }
}
