// SPDX-License-Identifier: MIT
// Auto-generated by ESBMC 8.2.0
// Foundry coverage test reconstructed from ESBMC counterexamples.
// Calls marked [revert-tolerant] are wrapped in try/catch: ESBMC could
// not confirm the call's outcome, so an undetected revert (e.g.
// require(cond, CustomError)) does not FAIL the assertion-free replay.
// The wrap does NOT assert a revert; a non-reverting call runs normally.
pragma solidity >=0.8.0;

import {Test} from "forge-std/Test.sol";
import {Cov} from "./contract.sol";

contract CovCovTest is Test {
  Cov c0;
  function setUp() public {
    c0 = new Cov();
  }
  function test_cov_0() public {
    // [revert-tolerant] outcome not asserted
    try c0.set(115792089237316195423570985008687907853269984665640564039457584007913129639935, true) {} catch {}
  }
  function test_cov_1() public {
    // [revert-tolerant] outcome not asserted
    try c0.set(115792089237316195423570985008687907853269984665640564039457584007913129639935, false) {} catch {}
  }
}
