// SPDX-License-Identifier: MIT
// Auto-generated by ESBMC 8.2.0
// Foundry coverage test reconstructed from ESBMC counterexamples.
pragma solidity >=0.8.0;

import {Test} from "forge-std/Test.sol";
import {Vault} from "./Vault.sol";

contract VaultCovTest is Test {
  Vault c0;
  function setUp() public {
    c0 = new Vault();
  }
  function test_cov_0() public {
    c0.withdraw(115792089237316195423570985008687907853269984665640564039457584007913129639935);
  }
  function test_cov_1() public {
    c0.withdraw(1000);
  }
  function test_cov_2() public {
    c0.adjust(-57896044618658097711785492504343953926634992332820282019728792003956564819968);
  }
  function test_cov_3() public {
    c0.adjust(0);
  }
}
