#!/usr/bin/env python3
"""Regression for the stage-4 PUT driver's ENTRY-STATE establishment.

WHY THIS FILE EXISTS, and what it pins.

A certified region is a statement about a SLICE. The slice is named by two
things that arrive through different arguments and had, until this test existed,
two different fates:

  * a REGION bound `state.<v> in [lo, hi]`, which `build_put` established with a
    read-modify-write `vm.store`;
  * a PIN `state.<v> == k`, which `build_put` printed in the header and
    otherwise DROPPED.

A pin is `[k, k]` -- the same statement, arrived at because the operator named
the value rather than because the ladder measured it -- and `main()` already
concatenates the two when it writes the assert spec, so ESBMC has been answering
about the pinned value all along. Only the emitted test disagreed.

MEASURED, and this is the failure the omission produced. On
`FeeVault.setDiscount` the guard is `msg.sender == owner`. That is a
cross-coordinate relation, out of scope by Definition 6, so the success path
certifies only with `owner` PINNED -- which turns it into
coordinate-equals-constant. `owner` is therefore a pin on every run that
certifies that path, never a region bound. The emitted concrete case pranks
`msg.sender = 0` and leaves `owner` at whatever the constructor gave it (the
test contract's own address, since `owner = msg.sender` at deployment), and
forge reports:

    [FAIL: EvmError: Revert] test_cov_0()

i.e. the require the case was generated to walk PAST rejects it. With the pin
established the same path's PUT is green over 256 fuzz runs, and goes red on a
mutant that writes an extra state variable -- so the establishment is what makes
the test be about the certified execution at all.

TWO DIRECTIONS, because one of them is the whole point:

  * a pin whose variable HAS a storage slot must produce a `vm.store` and be
    marked ESTABLISHED in the header;
  * a pin whose variable has NO slot (a `constant`/`immutable`) must NOT be
    silently ignored -- it goes into `state_skipped` with a reason and the
    header says NOT ESTABLISHED, because "this test is not known to be inside
    the certified slice" has to be visible on the test rather than inferred
    from the absence of a line.

Pure-function: no ESBMC, no solver, no forge, no clock. The emitted-file fixture
below is a VERBATIM capture of the emitter's own output for this contract
(`--generate-foundry-testcase` on bench/FeeVault), warning banner included; a
paraphrased one could drift from the parser it is here to exercise.
"""

import os
import sys
import tempfile

sys.path.insert(0, __file__.rsplit("/", 1)[0])

from solidity_path_put import (EmittedFile, build_put,   # noqa: E402
                               check_esbmc_args, cell_of,
                               truncated_loops, unwindset_args)


# VERBATIM captures. Shape 1 is the assert gate's refusal, semicolon-joined on
# ONE line (aqua Aqua.dock, notes/coverage/put_roundtrip); shape 2 is the
# under-report warning, one line per loop (FarmingPool.exit, reproduced by hand
# from that unit's own cert.json). They are DIFFERENT sentences from different
# code paths, and a parser written for one and pointed at the other never fires.
TRUNC_SHAPE_1 = (
    "[put]   ladder REFUSED: ERROR: --path-cov-assert: RESULT: "
    "UNDECIDED-TRUNCATED -- the non-vacuity witness for path enc=12 did NOT "
    "come back refuted ... Loops truncated: loop 1 at file "
    "/home/samson/workspace/esbmc/src/c2goto/library/stdlib.c line 38 column 3 "
    "function __ESBMC_atexit_handler; loop 62 at file "
    "notes/coverage/inputs/aqua__Aqua.flat.sol line 2258 function dock; loop 64 "
    "at file /home/samson/workspace/esbmc/src/c2goto/library/string.c line 298 "
    "column 3 function __memset_impl")

TRUNC_SHAPE_2 = """WARNING: Coverage may be UNDER-REPORTED: 2 loop(s) hit the unwind bound while --no-unwinding-assertions was active, so the paths that needed more iterations were silently assumed away. Goals reachable only through those paths are counted as uncovered. Raise --unwind, use --unwindset/--unwindsetname for the specific loop, or switch to --k-induction / --incremental-bmc. Loops truncated:
WARNING:   loop 55 at file /home/samson/workspace/esbmc/src/c2goto/library/solidity/solidity_string.c line 206 column 5 function _str_assign
WARNING:   loop 56 at file /home/samson/workspace/esbmc/src/c2goto/library/solidity/solidity_string.c line 209 column 5 function _str_assign"""


# VERBATIM: bench/FeeVault, `--generate-foundry-testcase --focus-function
# setDiscount --solidity-max-tx 1`. Do not rewrap or tidy -- EmittedFile parses
# this text, so its exact shape is the fixture.
EMITTED = """\
// SPDX-License-Identifier: MIT
// Auto-generated by ESBMC 8.2.0
// Foundry coverage test reconstructed from ESBMC counterexamples.
pragma solidity >=0.8.0;

import {Test} from "forge-std/Test.sol";
import {FeeVault} from "./FeeVault.sol";

contract FeeVaultCovTest is Test {
  FeeVault c0;
  function setUp() public {
    c0 = new FeeVault();
  }
  // claim: sol:@C@FeeVault@F@setDiscount#61:path:7
  function test_cov_0() public {
    vm.prank(address(uint160(0)));
    // [asserted] path exits normally; a revert fails the test
    c0.setDiscount(address(uint160(0)), 250);
  }
}
"""

# What solc reports for FeeVault: {var: (slot, offset, bytes)}. `feeBps` and
# `maxFee` are `constant` and are ABSENT, which is the fact the second direction
# below rests on.
LAYOUT = {"owner": (0, 0, 20), "feeReceiver": (1, 0, 20)}

PARAMS = [("u", "address"), ("bps", "uint16")]

LADDER = [("owner", "post == pre", "HOLDS"),
          ("feeReceiver", "post == pre", "HOLDS")]


def make_case():
    fd, path = tempfile.mkstemp(suffix=".cov.t.sol")
    with os.fdopen(fd, "w") as f:
        f.write(EMITTED)
    try:
        em = EmittedFile(path)
    finally:
        os.unlink(path)
    case = em.case_for("sol:@C@FeeVault@F@setDiscount#61", 7)
    assert case is not None, "fixture: the emitted case for enc=7 was not found"
    return em, case


def check(cond, msg):
    if not cond:
        print(f"FAIL: {msg}")
        return 1
    print(f"ok: {msg}")
    return 0


def test_pin_with_a_slot_is_established():
    """`state.owner == 0` arrives as a PIN and must reach the test."""
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250),
                "u": (0, (1 << 160) - 1)},
        holes={}, pins={"state.owner": 0, "msg.value": 0},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is not None, "a PUT is produced")
    text = "\n".join(put or [])
    bad += check(stats["state_stored"] == ["state.owner := 0"],
                 f"the pin is established: {stats['state_stored']}")
    bad += check("vm.store(address(c0), bytes32(uint256(0))" in text,
                 "a vm.store at owner's slot 0 is emitted")
    bad += check("PIN state.owner == 0   [ESTABLISHED by vm.store below]"
                 in text, "the header marks the pin ESTABLISHED")
    # msg.value is NOT a state pin and must not grow a store.
    bad += check("PIN msg.value == 0\n" in text + "\n",
                 "a non-state pin keeps its plain header line")
    # The two declared parameters are still lifted -- establishing a pin must
    # not cost the fuzz coordinates.
    bad += check(stats["lifted"] == ["u", "bps"],
                 f"both parameters are still lifted: {stats['lifted']}")
    return bad


def test_pin_without_a_slot_is_reported_not_dropped():
    """`state.feeBps == 250` is a `constant`: no slot, and it must SAY so."""
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={"state.feeBps": 250},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    text = "\n".join(put or [])
    bad += check(stats["state_stored"] == [],
                 "nothing is stored for a variable with no slot")
    bad += check(any(s.startswith("state.feeBps ")
                     for s in stats["state_skipped"]),
                 f"the unreachable pin is REPORTED: {stats['state_skipped']}")
    bad += check("PIN state.feeBps == 250   [NOT ESTABLISHED" in text,
                 "the header marks the pin NOT ESTABLISHED")
    return bad


def test_region_bound_still_wins_over_a_duplicate_pin():
    """A name in BOTH region and pins must be established ONCE, by the region.

    Two ledgers of one coordinate is the shape this project has paid for
    before: the region bound is the measured statement and the pin is the
    operator's, so a duplicate must not emit two stores whose order decides the
    entry state.
    """
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1),
                "state.owner": (7, 7)},
        holes={}, pins={"state.owner": 0},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    text = "\n".join(put or [])
    bad = 0
    bad += check(stats["state_stored"] == ["state.owner := 7"],
                 f"the REGION bound wins, once: {stats['state_stored']}")
    bad += check(text.count("vm.store(address(c0), bytes32(uint256(0))") == 1,
                 "exactly one store lands on owner's slot")
    return bad


def test_env_agreement_emits_when_the_preamble_matches():
    """`msg.sender in [0, 0]` against a preamble that pranks 0: EMIT.

    This is the FeeVault enc=7 case verbatim, and it is here as the control.
    A gate that only ever refuses is indistinguishable from one that is broken,
    and this fixture is what makes the refusal below a discriminator rather than
    a constant.
    """
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1),
                "msg.sender": (0, 0)},
        holes={}, pins={"msg.value": 0},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is not None,
                 f"agreement emits a PUT (notes: {notes})")
    bad += check(stats and not stats.get("env_unchecked"),
                 "nothing is reported unchecked when both are comparable")
    return bad


def test_env_disagreement_refuses():
    """`msg.sender in [1, 1]` against the SAME preamble: REFUSE.

    The emitted case pranks 0. Emitting would produce a test that runs under a
    caller the certification never spoke about -- and it would look exactly like
    the passing case above, which is why this is a refusal and not a note.
    """
    em, case = make_case()
    notes = []
    put, _stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1),
                "msg.sender": (1, 1)},
        holes={}, pins={}, params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is None, "a disagreeing environment REFUSES")
    bad += check(any("msg.sender is certified at 1" in n and "sets it to 0" in n
                     for n in notes),
                 f"the refusal names both values: {notes}")
    return bad


def test_env_value_pin_disagreement_refuses():
    """`msg.value == 7` against a call carrying no `{value:}`: REFUSE.

    The ABSENCE of a value option is 0 -- a fact about the EVM, not a guess --
    so this is a genuine disagreement and not an unknown.
    """
    em, case = make_case()
    notes = []
    put, _stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={"msg.value": 7}, params=PARAMS, emitted=em, case=case,
        layout=LAYOUT, ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is None, "a disagreeing msg.value REFUSES")
    bad += check(any("msg.value is certified at 7" in n for n in notes),
                 f"the refusal names msg.value: {notes}")
    return bad


def test_uncomparable_env_quantity_is_disclosed_not_ignored():
    """`block.timestamp == 42` is neither checkable nor silently fine."""
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1),
                "block.timestamp": (42, 42)},
        holes={}, pins={}, params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is not None,
                 "an uncomparable quantity does not block emission")
    bad += check(any("block.timestamp == 42 is NOT CHECKED" in s
                     for s in (stats or {}).get("env_unchecked", [])),
                 f"it is disclosed: {(stats or {}).get('env_unchecked')}")
    bad += check("environment NOT CHECKED: block.timestamp == 42"
                 in "\n".join(put or []),
                 "and the disclosure is ON the emitted test, not only in stats")
    return bad


def test_esbmc_arg_passthrough_admits_unwindset_and_refuses_strategies():
    """`--unwindset` through, every strategy flag stopped.

    Both directions, because a passthrough that refuses everything is as useless
    as one that refuses nothing. `--unwindset` is the one the ladder's own
    UNDECIDED-TRUNCATED refusal names, and it moves only the symex side -- a
    SUPERSET of executions, so it cannot make a path look infeasible that is not.
    The strategy flags change which claims exist AND the bound they are answered
    under, and the only measurement of that ran on a snapshot binary this note
    itself marks unverified on newer builds.
    """
    bad = 0
    bad += check(check_esbmc_args(["--unwindset", "64:512"]) is None,
                 "--unwindset passes through")
    bad += check(check_esbmc_args(["--partial-loops"]) is None,
                 "--partial-loops passes through (the third repair the tool "
                 "names)")
    bad += check(check_esbmc_args([]) is None, "no extra args is fine")
    for flag in ("--k-induction", "--incremental-bmc", "--inductive-step",
                 "--loop-invariant", "--falsification", "--termination",
                 "--forward-condition", "--k-induction-parallel"):
        r = check_esbmc_args(["--unwindset", "64:512", flag])
        bad += check(r is not None and flag in r,
                     f"{flag} is refused even beside a legitimate flag")
    return bad


def test_the_cell_is_named_and_an_unsettled_one_says_so():
    """Which of the two settled command lines a run is, or neither.

    INVOCATION_DECISIONS.md forbids quoting a run of one cell into the other's
    table. The enforcement this driver can offer is that the artefact NAMES its
    cell -- and that a configuration matching neither is called UNNAMED rather
    than being silently filed under whichever is closer, which is how a
    focused tx=2 run would end up quoted as the method's reach.
    """
    bad = 0
    n, r = cell_of("whole", 2)
    bad += check(n == "ARTEFACT" and "gate table" in r,
                 f"whole/tx=2 is the ARTEFACT cell, with its rule: {n}")
    n, r = cell_of("focus", 1)
    bad += check(n == "GATE" and "reach" in r,
                 f"focus/tx=1 is the GATE cell, with its rule: {n}")
    for scope, tx in (("focus", 2), ("whole", 1), ("whole", 3)):
        n, r = cell_of(scope, tx)
        bad += check(n == "UNNAMED" and "belongs to no table" in r,
                     f"{scope}/tx={tx} is UNNAMED, not filed under a neighbour")
    return bad


def test_a_widened_ladder_says_which_half_it_applies_to():
    """The oracle and the body come from two runs at different symex bounds.

    The emit run supplies the preamble and the concrete case and happens BEFORE
    any loop has been named, so it never carries the widening. Recording the
    widened flags as "the run's configuration" -- which the first version did --
    claims both runs used them, and that is a false provenance on the one
    artefact whose whole value is that its provenance is checkable.
    """
    em, case = make_case()
    notes = []
    put, _stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={}, params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes, cell=cell_of("focus", 1),
        unwind=["--unwindset", "64:512"])
    text = "\n".join(put or [])
    bad = check("LADDER WIDENED: --unwindset 64:512" in text,
                "the widening is named on the test")
    bad += check("ASSERTION LADDER run only" in text,
                 "and it says which half of the test it applies to")
    # MUST NOT FIRE: an un-widened run must not grow the disclaimer, or every
    # PUT would carry a caveat about something that did not happen.
    put2, _ = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={}, params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=[], cell=cell_of("focus", 1), unwind=[])
    bad += check("LADDER WIDENED" not in "\n".join(put2 or []),
                 "an un-widened run carries no such line")
    return bad


def test_the_emitted_test_carries_its_cell():
    """A PUT that does not say which cell produced it is quotable into both."""
    em, case = make_case()
    notes = []
    put, _stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={}, params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes, cell=cell_of("focus", 1))
    text = "\n".join(put or [])
    return check("// CELL GATE --" in text,
                 "the cell is written onto the emitted test")


def test_both_truncation_shapes_are_read():
    """The tool NAMES the loop it cut, in two different sentences.

    This is the mechanism INVOCATION_DECISIONS.md records as missing ("we still
    have no mechanism for knowing how many unwinds are needed"). It was not
    missing from the tool, only from every consumer.
    """
    bad = 0
    l1, s1 = truncated_loops(TRUNC_SHAPE_1)
    bad += check([x[0] for x in sorted(l1)] == [1, 62, 64],
                 f"shape 1 (assert gate, one line): {[x[0] for x in sorted(l1)]}")
    bad += check(s1["assert-gate"] == 3 and s1["under-report-warning"] == 0,
                 f"shape 1 is attributed to its own branch: {s1}")
    bad += check(any(fn == "__memset_impl" for _i, _f, _l, fn in l1),
                 "the library loop the measured fix widened is named")

    l2, s2 = truncated_loops(TRUNC_SHAPE_2)
    bad += check([x[0] for x in sorted(l2)] == [55, 56],
                 f"shape 2 (under-report warning, one per line): "
                 f"{[x[0] for x in sorted(l2)]}")
    bad += check(s2["under-report-warning"] == 2 and s2["assert-gate"] == 0,
                 f"shape 2 is attributed to its own branch: {s2}")

    # MUST NOT FIRE. A log with no truncation report must yield nothing, or the
    # ladder would widen loops nobody cut and every run would look truncated.
    l3, s3 = truncated_loops(
        "--path-cov-assert: bal: post == pre  HOLDS\n"
        "some prose that mentions a loop 99 at file x line 1 function f\n")
    bad += check(l3 == [] and sum(s3.values()) == 0,
                 f"prose outside either report is NOT read as a truncation: "
                 f"{l3}")
    return bad


def test_the_ladder_widens_every_named_loop():
    """--unwindset per named loop, and only the symex side."""
    loops, _ = truncated_loops(TRUNC_SHAPE_1)
    got = unwindset_args(loops, 512)
    want = ["--unwindset", "1:512", "--unwindset", "62:512",
            "--unwindset", "64:512"]
    bad = check(got == want, f"one --unwindset per loop, sorted: {got}")
    bad += check("--unwind" not in got or all(
        g != "--unwind" for g in got),
        "the ENUMERATION bound (--unwind) is never touched: widening it would "
        "change the goal set, i.e. what is being measured")
    return bad


# ---------------------------------------------------------------------------
# The unit's OWN RETURN VALUE as an oracle
# ---------------------------------------------------------------------------
#
# WHAT WOULD LOOK IDENTICAL IF THIS WERE BROKEN, which is what each case below
# is built to separate:
#
#   * the rungs never rendered at all  -> no assertion, and a PUT that looks
#     exactly like one whose unit returns nothing. Cases 1/3/6 fail on absence.
#   * the rungs rendered UNCONDITIONALLY -> an assertion certified about a
#     value the execution never produced, because every return rung carries
#     `|| !retset` and can hold for want of a returned value. Case 2 is the
#     must-flip: the SAME rows with `retlive` HOLDS instead of REFUTED must
#     produce nothing, and must say why.
#   * the binding spliced into a `try`/`catch` or an expectRevert call -> the
#     R0 exit-kind expectation, which this whole lifting route exists to
#     preserve, replaced by a different statement. Cases 5 and 7.

RETLIVE = "a value IS returned on this path (REFUTED == yes)"


def _ret_put(ladder_rows, rettypes, layout=None):
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={}, params=PARAMS, emitted=em, case=case,
        layout=LAYOUT if layout is None else layout,
        ladder_rows=ladder_rows, notes=notes, rettypes=rettypes)
    return "\n".join(put or []), stats, notes


def test_return_rung_is_bound_and_asserted():
    """A HOLDS return rung, with `retlive` REFUTED: BIND and ASSERT."""
    text, stats, _n = _ret_put(
        LADDER + [("return", RETLIVE, "REFUTED"),
                  ("return", "return != 0", "HOLDS")],
        [("", "uint256")])
    bad = 0
    bad += check("uint256 _put_ret = c0.setDiscount(" in text,
                 "the call is bound to a typed local")
    bad += check("assertTrue(uint256(_put_ret) != 0" in text,
                 "the HOLDS rung becomes an assertion")
    bad += check(stats["return_asserts"] == 1 and stats["state_asserts"] == 2,
                 f"the two oracle sources are counted apart: {stats['asserts']} "
                 f"= {stats['state_asserts']} state + "
                 f"{stats['return_asserts']} return")
    bad += check("over the unit's OWN RETURN" in text,
                 "the header says the oracle has a return-value half")
    return bad


def test_a_retlive_that_HOLDS_kills_every_return_rung():
    """THE MUST-FLIP. Same rows, `retlive` HOLDS: nothing may be emitted.

    `retlive` asserts `!retset`, so HOLDS means NO execution of this path was
    shown to reach a return -- and every other return rung, which all carry
    `|| !retset`, is then holding for want of a returned value. Rendering one
    would assert something about a value that was never produced. The two
    inputs differ in ONE token, so a renderer that ignored the witness would
    pass the case above and fail here.
    """
    text, stats, _n = _ret_put(
        LADDER + [("return", RETLIVE, "HOLDS"),
                  ("return", "return != 0", "HOLDS")],
        [("", "uint256")])
    bad = 0
    bad += check("_put_ret" not in text,
                 "no binding is emitted")
    bad += check(stats["return_asserts"] == 0,
                 f"no return assertion: {stats['return_asserts']}")
    bad += check(any("retlive" in s and "VACUOUSLY" in s
                     for s in stats["oracle_skipped"]),
                 f"and the drop NAMES the witness: {stats['oracle_skipped']}")
    return bad


def test_a_bool_return_uses_assertTrue_not_a_cast():
    """`uint256(<bool>)` is not a Solidity conversion; the rung shape differs."""
    text, stats, _n = _ret_put(
        LADDER + [("return", RETLIVE, "REFUTED"),
                  ("return", "return == true", "HOLDS")],
        [("", "bool")])
    bad = 0
    bad += check("bool _put_ret = c0.setDiscount(" in text,
                 "the local is declared bool")
    bad += check("assertTrue(_put_ret," in text and "uint256(_put_ret)"
                 not in text,
                 "asserted directly, with no uint256 cast")
    bad += check(stats["return_asserts"] == 1,
                 f"one return assertion: {stats['return_asserts']}")
    return bad


def test_a_tuple_return_is_not_bound_and_says_so():
    """Two declared return values cannot go into one local."""
    text, stats, _n = _ret_put(
        LADDER + [("return", RETLIVE, "REFUTED"),
                  ("return", "return != 0", "HOLDS")],
        [("", "uint248"), ("", "uint8")])
    bad = 0
    bad += check("_put_ret" not in text, "nothing is bound")
    bad += check(any("2 return value(s)" in s
                     for s in stats["oracle_skipped"]),
                 f"the drop names the count: {stats['oracle_skipped']}")
    return bad


def test_an_unbindable_return_type_is_reported():
    """A type this emitter cannot cast is DROPPED by name, never guessed."""
    _t, stats, _n = _ret_put(
        LADDER + [("return", RETLIVE, "REFUTED"),
                  ("return", "return != 0", "HOLDS")],
        [("", "string memory")])
    return check(any("string memory" in s for s in stats["oracle_skipped"]),
                 f"the drop names the type: {stats['oracle_skipped']}")


def test_bind_return_refuses_the_exit_kind_shapes():
    """`try`/`catch` and an already-bound call are the two shapes that must
    survive untouched.

    Tested on `bind_return` directly rather than through a captured emitted
    file: the property is the guard, and the fixture above has only the bare
    shape. Constructed input, and labelled as such.
    """
    from solidity_path_put import bind_return  # noqa: E402
    bad = 0
    ln, why = bind_return("    try c0.f(1) { } catch { }", "f", "uint256", "_r")
    bad += check(ln is None and "try" in (why or ""),
                 f"a try/catch statement is refused: {why}")
    ln, why = bind_return("    uint256 z = c0.f(1);", "f", "uint256", "_r")
    bad += check(ln is None and "already binds" in (why or ""),
                 f"an already-bound call is refused: {why}")
    ln, why = bind_return("    c0.f(1);", "f", "uint256", "_r")
    bad += check(ln == "    uint256 _r = c0.f(1);",
                 f"a bare asserted call IS bound: {ln}")
    return bad


def test_a_return_only_oracle_still_reaches_the_test():
    """No state rung at all: the return assertions must still be written.

    This is the guard that used to read `if post_reads:` -- equivalent only
    while every assertion came from a state rung. A unit whose only surviving
    rung is a return rung has no post-read, and the header would have
    announced assertions the body did not contain.
    """
    text, stats, _n = _ret_put(
        [("return", RETLIVE, "REFUTED"),
         ("return", "return in [1, 9]", "HOLDS")],
        [("", "uint256")])
    bad = 0
    bad += check(stats["state_asserts"] == 0,
                 "no state rung was supplied")
    bad += check(stats["return_asserts"] == 2,
                 f"the interval rung is two assertions: "
                 f"{stats['return_asserts']}")
    bad += check("assertGe(uint256(_put_ret), 1" in text
                 and "assertLe(uint256(_put_ret), 9" in text,
                 "and both are in the emitted body")
    return bad


def test_a_refuted_return_rung_is_never_asserted():
    """REFUTED is the ladder working, not an oracle."""
    text, stats, _n = _ret_put(
        LADDER + [("return", RETLIVE, "REFUTED"),
                  ("return", "return == 0", "REFUTED"),
                  ("return", "return != 0", "HOLDS")],
        [("", "uint256")])
    bad = 0
    bad += check("assertEq(uint256(_put_ret), 0" not in text,
                 "the REFUTED rung produces no assertion")
    bad += check(stats["return_asserts"] == 1,
                 f"only the HOLDS one survives: {stats['return_asserts']}")
    return bad


def main():
    bad = 0
    for t in (test_both_truncation_shapes_are_read,
              test_the_ladder_widens_every_named_loop,
              test_a_widened_ladder_says_which_half_it_applies_to,
              test_the_cell_is_named_and_an_unsettled_one_says_so,
              test_the_emitted_test_carries_its_cell,
              test_esbmc_arg_passthrough_admits_unwindset_and_refuses_strategies,
              test_pin_with_a_slot_is_established,
              test_pin_without_a_slot_is_reported_not_dropped,
              test_region_bound_still_wins_over_a_duplicate_pin,
              test_env_agreement_emits_when_the_preamble_matches,
              test_env_disagreement_refuses,
              test_env_value_pin_disagreement_refuses,
              test_uncomparable_env_quantity_is_disclosed_not_ignored,
              test_return_rung_is_bound_and_asserted,
              test_a_retlive_that_HOLDS_kills_every_return_rung,
              test_a_bool_return_uses_assertTrue_not_a_cast,
              test_a_tuple_return_is_not_bound_and_says_so,
              test_an_unbindable_return_type_is_reported,
              test_bind_return_refuses_the_exit_kind_shapes,
              test_a_return_only_oracle_still_reaches_the_test,
              test_a_refuted_return_rung_is_never_asserted):
        print(f"--- {t.__name__}")
        bad += t()
    if bad:
        print(f"\n{bad} check(s) FAILED")
        return 1
    print("\nall checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
