#!/usr/bin/env python3
"""Regression for the stage-4 PUT driver's ENTRY-STATE establishment.

WHY THIS FILE EXISTS, and what it pins.

A certified region is a statement about a SLICE. The slice is named by two
things that arrive through different arguments and had, until this test existed,
two different fates:

  * a REGION bound `state.<v> in [lo, hi]`, which `build_put` established with a
    read-modify-write `vm.store`;
  * a PIN `state.<v> == k`, which `build_put` printed in the header and
    otherwise DROPPED.

A pin is `[k, k]` -- the same statement, arrived at because the operator named
the value rather than because the ladder measured it -- and `main()` already
concatenates the two when it writes the assert spec, so ESBMC has been answering
about the pinned value all along. Only the emitted test disagreed.

MEASURED, and this is the failure the omission produced. On
`FeeVault.setDiscount` the guard is `msg.sender == owner`. That is a
cross-coordinate relation, out of scope by Definition 6, so the success path
certifies only with `owner` PINNED -- which turns it into
coordinate-equals-constant. `owner` is therefore a pin on every run that
certifies that path, never a region bound. The emitted concrete case pranks
`msg.sender = 0` and leaves `owner` at whatever the constructor gave it (the
test contract's own address, since `owner = msg.sender` at deployment), and
forge reports:

    [FAIL: EvmError: Revert] test_cov_0()

i.e. the require the case was generated to walk PAST rejects it. With the pin
established the same path's PUT is green over 256 fuzz runs, and goes red on a
mutant that writes an extra state variable -- so the establishment is what makes
the test be about the certified execution at all.

TWO DIRECTIONS, because one of them is the whole point:

  * a pin whose variable HAS a storage slot must produce a `vm.store` and be
    marked ESTABLISHED in the header;
  * a pin whose variable has NO slot (a `constant`/`immutable`) must NOT be
    silently ignored -- it goes into `state_skipped` with a reason and the
    header says NOT ESTABLISHED, because "this test is not known to be inside
    the certified slice" has to be visible on the test rather than inferred
    from the absence of a line.

Pure-function: no ESBMC, no solver, no forge, no clock. The emitted-file fixture
below is a VERBATIM capture of the emitter's own output for this contract
(`--generate-foundry-testcase` on bench/FeeVault), warning banner included; a
paraphrased one could drift from the parser it is here to exercise.
"""

import os
import sys
import tempfile

sys.path.insert(0, __file__.rsplit("/", 1)[0])

from solidity_path_put import (EmittedFile, build_put,   # noqa: E402
                               check_esbmc_args, cell_of)


# VERBATIM: bench/FeeVault, `--generate-foundry-testcase --focus-function
# setDiscount --solidity-max-tx 1`. Do not rewrap or tidy -- EmittedFile parses
# this text, so its exact shape is the fixture.
EMITTED = """\
// SPDX-License-Identifier: MIT
// Auto-generated by ESBMC 8.2.0
// Foundry coverage test reconstructed from ESBMC counterexamples.
pragma solidity >=0.8.0;

import {Test} from "forge-std/Test.sol";
import {FeeVault} from "./FeeVault.sol";

contract FeeVaultCovTest is Test {
  FeeVault c0;
  function setUp() public {
    c0 = new FeeVault();
  }
  // claim: sol:@C@FeeVault@F@setDiscount#61:path:7
  function test_cov_0() public {
    vm.prank(address(uint160(0)));
    // [asserted] path exits normally; a revert fails the test
    c0.setDiscount(address(uint160(0)), 250);
  }
}
"""

# What solc reports for FeeVault: {var: (slot, offset, bytes)}. `feeBps` and
# `maxFee` are `constant` and are ABSENT, which is the fact the second direction
# below rests on.
LAYOUT = {"owner": (0, 0, 20), "feeReceiver": (1, 0, 20)}

PARAMS = [("u", "address"), ("bps", "uint16")]

LADDER = [("owner", "post == pre", "HOLDS"),
          ("feeReceiver", "post == pre", "HOLDS")]


def make_case():
    fd, path = tempfile.mkstemp(suffix=".cov.t.sol")
    with os.fdopen(fd, "w") as f:
        f.write(EMITTED)
    try:
        em = EmittedFile(path)
    finally:
        os.unlink(path)
    case = em.case_for("sol:@C@FeeVault@F@setDiscount#61", 7)
    assert case is not None, "fixture: the emitted case for enc=7 was not found"
    return em, case


def check(cond, msg):
    if not cond:
        print(f"FAIL: {msg}")
        return 1
    print(f"ok: {msg}")
    return 0


def test_pin_with_a_slot_is_established():
    """`state.owner == 0` arrives as a PIN and must reach the test."""
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250),
                "u": (0, (1 << 160) - 1)},
        holes={}, pins={"state.owner": 0, "msg.value": 0},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is not None, "a PUT is produced")
    text = "\n".join(put or [])
    bad += check(stats["state_stored"] == ["state.owner := 0"],
                 f"the pin is established: {stats['state_stored']}")
    bad += check("vm.store(address(c0), bytes32(uint256(0))" in text,
                 "a vm.store at owner's slot 0 is emitted")
    bad += check("PIN state.owner == 0   [ESTABLISHED by vm.store below]"
                 in text, "the header marks the pin ESTABLISHED")
    # msg.value is NOT a state pin and must not grow a store.
    bad += check("PIN msg.value == 0\n" in text + "\n",
                 "a non-state pin keeps its plain header line")
    # The two declared parameters are still lifted -- establishing a pin must
    # not cost the fuzz coordinates.
    bad += check(stats["lifted"] == ["u", "bps"],
                 f"both parameters are still lifted: {stats['lifted']}")
    return bad


def test_pin_without_a_slot_is_reported_not_dropped():
    """`state.feeBps == 250` is a `constant`: no slot, and it must SAY so."""
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={"state.feeBps": 250},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    text = "\n".join(put or [])
    bad += check(stats["state_stored"] == [],
                 "nothing is stored for a variable with no slot")
    bad += check(any(s.startswith("state.feeBps ")
                     for s in stats["state_skipped"]),
                 f"the unreachable pin is REPORTED: {stats['state_skipped']}")
    bad += check("PIN state.feeBps == 250   [NOT ESTABLISHED" in text,
                 "the header marks the pin NOT ESTABLISHED")
    return bad


def test_region_bound_still_wins_over_a_duplicate_pin():
    """A name in BOTH region and pins must be established ONCE, by the region.

    Two ledgers of one coordinate is the shape this project has paid for
    before: the region bound is the measured statement and the pin is the
    operator's, so a duplicate must not emit two stores whose order decides the
    entry state.
    """
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1),
                "state.owner": (7, 7)},
        holes={}, pins={"state.owner": 0},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    text = "\n".join(put or [])
    bad = 0
    bad += check(stats["state_stored"] == ["state.owner := 7"],
                 f"the REGION bound wins, once: {stats['state_stored']}")
    bad += check(text.count("vm.store(address(c0), bytes32(uint256(0))") == 1,
                 "exactly one store lands on owner's slot")
    return bad


def test_env_agreement_emits_when_the_preamble_matches():
    """`msg.sender in [0, 0]` against a preamble that pranks 0: EMIT.

    This is the FeeVault enc=7 case verbatim, and it is here as the control.
    A gate that only ever refuses is indistinguishable from one that is broken,
    and this fixture is what makes the refusal below a discriminator rather than
    a constant.
    """
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1),
                "msg.sender": (0, 0)},
        holes={}, pins={"msg.value": 0},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is not None,
                 f"agreement emits a PUT (notes: {notes})")
    bad += check(stats and not stats.get("env_unchecked"),
                 "nothing is reported unchecked when both are comparable")
    return bad


def test_env_disagreement_refuses():
    """`msg.sender in [1, 1]` against the SAME preamble: REFUSE.

    The emitted case pranks 0. Emitting would produce a test that runs under a
    caller the certification never spoke about -- and it would look exactly like
    the passing case above, which is why this is a refusal and not a note.
    """
    em, case = make_case()
    notes = []
    put, _stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1),
                "msg.sender": (1, 1)},
        holes={}, pins={}, params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is None, "a disagreeing environment REFUSES")
    bad += check(any("msg.sender is certified at 1" in n and "sets it to 0" in n
                     for n in notes),
                 f"the refusal names both values: {notes}")
    return bad


def test_env_value_pin_disagreement_refuses():
    """`msg.value == 7` against a call carrying no `{value:}`: REFUSE.

    The ABSENCE of a value option is 0 -- a fact about the EVM, not a guess --
    so this is a genuine disagreement and not an unknown.
    """
    em, case = make_case()
    notes = []
    put, _stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={"msg.value": 7}, params=PARAMS, emitted=em, case=case,
        layout=LAYOUT, ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is None, "a disagreeing msg.value REFUSES")
    bad += check(any("msg.value is certified at 7" in n for n in notes),
                 f"the refusal names msg.value: {notes}")
    return bad


def test_uncomparable_env_quantity_is_disclosed_not_ignored():
    """`block.timestamp == 42` is neither checkable nor silently fine."""
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1),
                "block.timestamp": (42, 42)},
        holes={}, pins={}, params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is not None,
                 "an uncomparable quantity does not block emission")
    bad += check(any("block.timestamp == 42 is NOT CHECKED" in s
                     for s in (stats or {}).get("env_unchecked", [])),
                 f"it is disclosed: {(stats or {}).get('env_unchecked')}")
    bad += check("environment NOT CHECKED: block.timestamp == 42"
                 in "\n".join(put or []),
                 "and the disclosure is ON the emitted test, not only in stats")
    return bad


def test_esbmc_arg_passthrough_admits_unwindset_and_refuses_strategies():
    """`--unwindset` through, every strategy flag stopped.

    Both directions, because a passthrough that refuses everything is as useless
    as one that refuses nothing. `--unwindset` is the one the ladder's own
    UNDECIDED-TRUNCATED refusal names, and it moves only the symex side -- a
    SUPERSET of executions, so it cannot make a path look infeasible that is not.
    The strategy flags change which claims exist AND the bound they are answered
    under, and the only measurement of that ran on a snapshot binary this note
    itself marks unverified on newer builds.
    """
    bad = 0
    bad += check(check_esbmc_args(["--unwindset", "64:512"]) is None,
                 "--unwindset passes through")
    bad += check(check_esbmc_args(["--partial-loops"]) is None,
                 "--partial-loops passes through (the third repair the tool "
                 "names)")
    bad += check(check_esbmc_args([]) is None, "no extra args is fine")
    for flag in ("--k-induction", "--incremental-bmc", "--inductive-step",
                 "--loop-invariant", "--falsification", "--termination",
                 "--forward-condition", "--k-induction-parallel"):
        r = check_esbmc_args(["--unwindset", "64:512", flag])
        bad += check(r is not None and flag in r,
                     f"{flag} is refused even beside a legitimate flag")
    return bad


def test_the_cell_is_named_and_an_unsettled_one_says_so():
    """Which of the two settled command lines a run is, or neither.

    INVOCATION_DECISIONS.md forbids quoting a run of one cell into the other's
    table. The enforcement this driver can offer is that the artefact NAMES its
    cell -- and that a configuration matching neither is called UNNAMED rather
    than being silently filed under whichever is closer, which is how a
    focused tx=2 run would end up quoted as the method's reach.
    """
    bad = 0
    n, r = cell_of("whole", 2)
    bad += check(n == "ARTEFACT" and "gate table" in r,
                 f"whole/tx=2 is the ARTEFACT cell, with its rule: {n}")
    n, r = cell_of("focus", 1)
    bad += check(n == "GATE" and "reach" in r,
                 f"focus/tx=1 is the GATE cell, with its rule: {n}")
    for scope, tx in (("focus", 2), ("whole", 1), ("whole", 3)):
        n, r = cell_of(scope, tx)
        bad += check(n == "UNNAMED" and "belongs to no table" in r,
                     f"{scope}/tx={tx} is UNNAMED, not filed under a neighbour")
    return bad


def test_the_emitted_test_carries_its_cell():
    """A PUT that does not say which cell produced it is quotable into both."""
    em, case = make_case()
    notes = []
    put, _stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={}, params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes, cell=cell_of("focus", 1))
    text = "\n".join(put or [])
    return check("// CELL GATE --" in text,
                 "the cell is written onto the emitted test")


def main():
    bad = 0
    for t in (test_the_cell_is_named_and_an_unsettled_one_says_so,
              test_the_emitted_test_carries_its_cell,
              test_esbmc_arg_passthrough_admits_unwindset_and_refuses_strategies,
              test_pin_with_a_slot_is_established,
              test_pin_without_a_slot_is_reported_not_dropped,
              test_region_bound_still_wins_over_a_duplicate_pin,
              test_env_agreement_emits_when_the_preamble_matches,
              test_env_disagreement_refuses,
              test_env_value_pin_disagreement_refuses,
              test_uncomparable_env_quantity_is_disclosed_not_ignored):
        print(f"--- {t.__name__}")
        bad += t()
    if bad:
        print(f"\n{bad} check(s) FAILED")
        return 1
    print("\nall checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
