#!/usr/bin/env python3
"""Regression for the stage-4 PUT driver's ENTRY-STATE establishment.

WHY THIS FILE EXISTS, and what it pins.

A certified region is a statement about a SLICE. The slice is named by two
things that arrive through different arguments and had, until this test existed,
two different fates:

  * a REGION bound `state.<v> in [lo, hi]`, which `build_put` established with a
    read-modify-write `vm.store`;
  * a PIN `state.<v> == k`, which `build_put` printed in the header and
    otherwise DROPPED.

A pin is `[k, k]` -- the same statement, arrived at because the operator named
the value rather than because the ladder measured it -- and `main()` already
concatenates the two when it writes the assert spec, so ESBMC has been answering
about the pinned value all along. Only the emitted test disagreed.

MEASURED, and this is the failure the omission produced. On
`FeeVault.setDiscount` the guard is `msg.sender == owner`. That is a
cross-coordinate relation, out of scope by Definition 6, so the success path
certifies only with `owner` PINNED -- which turns it into
coordinate-equals-constant. `owner` is therefore a pin on every run that
certifies that path, never a region bound. The emitted concrete case pranks
`msg.sender = 0` and leaves `owner` at whatever the constructor gave it (the
test contract's own address, since `owner = msg.sender` at deployment), and
forge reports:

    [FAIL: EvmError: Revert] test_cov_0()

i.e. the require the case was generated to walk PAST rejects it. With the pin
established the same path's PUT is green over 256 fuzz runs, and goes red on a
mutant that writes an extra state variable -- so the establishment is what makes
the test be about the certified execution at all.

TWO DIRECTIONS, because one of them is the whole point:

  * a pin whose variable HAS a storage slot must produce a `vm.store` and be
    marked ESTABLISHED in the header;
  * a pin whose variable has NO slot (a `constant`/`immutable`) must NOT be
    silently ignored -- it goes into `state_skipped` with a reason and the
    header says NOT ESTABLISHED, because "this test is not known to be inside
    the certified slice" has to be visible on the test rather than inferred
    from the absence of a line.

Pure-function: no ESBMC, no solver, no forge, no clock. The emitted-file fixture
below is a VERBATIM capture of the emitter's own output for this contract
(`--generate-foundry-testcase` on bench/FeeVault), warning banner included; a
paraphrased one could drift from the parser it is here to exercise.
"""

import os
import sys
import tempfile

sys.path.insert(0, __file__.rsplit("/", 1)[0])

from solidity_path_put import EmittedFile, build_put   # noqa: E402


# VERBATIM: bench/FeeVault, `--generate-foundry-testcase --focus-function
# setDiscount --solidity-max-tx 1`. Do not rewrap or tidy -- EmittedFile parses
# this text, so its exact shape is the fixture.
EMITTED = """\
// SPDX-License-Identifier: MIT
// Auto-generated by ESBMC 8.2.0
// Foundry coverage test reconstructed from ESBMC counterexamples.
pragma solidity >=0.8.0;

import {Test} from "forge-std/Test.sol";
import {FeeVault} from "./FeeVault.sol";

contract FeeVaultCovTest is Test {
  FeeVault c0;
  function setUp() public {
    c0 = new FeeVault();
  }
  // claim: sol:@C@FeeVault@F@setDiscount#61:path:7
  function test_cov_0() public {
    vm.prank(address(uint160(0)));
    // [asserted] path exits normally; a revert fails the test
    c0.setDiscount(address(uint160(0)), 250);
  }
}
"""

# What solc reports for FeeVault: {var: (slot, offset, bytes)}. `feeBps` and
# `maxFee` are `constant` and are ABSENT, which is the fact the second direction
# below rests on.
LAYOUT = {"owner": (0, 0, 20), "feeReceiver": (1, 0, 20)}

PARAMS = [("u", "address"), ("bps", "uint16")]

LADDER = [("owner", "post == pre", "HOLDS"),
          ("feeReceiver", "post == pre", "HOLDS")]


def make_case():
    fd, path = tempfile.mkstemp(suffix=".cov.t.sol")
    with os.fdopen(fd, "w") as f:
        f.write(EMITTED)
    try:
        em = EmittedFile(path)
    finally:
        os.unlink(path)
    case = em.case_for("sol:@C@FeeVault@F@setDiscount#61", 7)
    assert case is not None, "fixture: the emitted case for enc=7 was not found"
    return em, case


def check(cond, msg):
    if not cond:
        print(f"FAIL: {msg}")
        return 1
    print(f"ok: {msg}")
    return 0


def test_pin_with_a_slot_is_established():
    """`state.owner == 0` arrives as a PIN and must reach the test."""
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250),
                "u": (0, (1 << 160) - 1)},
        holes={}, pins={"state.owner": 0, "msg.value": 0},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    bad += check(put is not None, "a PUT is produced")
    text = "\n".join(put or [])
    bad += check(stats["state_stored"] == ["state.owner := 0"],
                 f"the pin is established: {stats['state_stored']}")
    bad += check("vm.store(address(c0), bytes32(uint256(0))" in text,
                 "a vm.store at owner's slot 0 is emitted")
    bad += check("PIN state.owner == 0   [ESTABLISHED by vm.store below]"
                 in text, "the header marks the pin ESTABLISHED")
    # msg.value is NOT a state pin and must not grow a store.
    bad += check("PIN msg.value == 0\n" in text + "\n",
                 "a non-state pin keeps its plain header line")
    # The two declared parameters are still lifted -- establishing a pin must
    # not cost the fuzz coordinates.
    bad += check(stats["lifted"] == ["u", "bps"],
                 f"both parameters are still lifted: {stats['lifted']}")
    return bad


def test_pin_without_a_slot_is_reported_not_dropped():
    """`state.feeBps == 250` is a `constant`: no slot, and it must SAY so."""
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1)},
        holes={}, pins={"state.feeBps": 250},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    bad = 0
    text = "\n".join(put or [])
    bad += check(stats["state_stored"] == [],
                 "nothing is stored for a variable with no slot")
    bad += check(any(s.startswith("state.feeBps ")
                     for s in stats["state_skipped"]),
                 f"the unreachable pin is REPORTED: {stats['state_skipped']}")
    bad += check("PIN state.feeBps == 250   [NOT ESTABLISHED" in text,
                 "the header marks the pin NOT ESTABLISHED")
    return bad


def test_region_bound_still_wins_over_a_duplicate_pin():
    """A name in BOTH region and pins must be established ONCE, by the region.

    Two ledgers of one coordinate is the shape this project has paid for
    before: the region bound is the measured statement and the pin is the
    operator's, so a duplicate must not emit two stores whose order decides the
    entry state.
    """
    em, case = make_case()
    notes = []
    put, stats = build_put(
        "FeeVault", "setDiscount", 7, 2, "sol:@C@FeeVault@F@setDiscount#61",
        region={"bps": (0, 250), "u": (0, (1 << 160) - 1),
                "state.owner": (7, 7)},
        holes={}, pins={"state.owner": 0},
        params=PARAMS, emitted=em, case=case, layout=LAYOUT,
        ladder_rows=LADDER, notes=notes)
    text = "\n".join(put or [])
    bad = 0
    bad += check(stats["state_stored"] == ["state.owner := 7"],
                 f"the REGION bound wins, once: {stats['state_stored']}")
    bad += check(text.count("vm.store(address(c0), bytes32(uint256(0))") == 1,
                 "exactly one store lands on owner's slot")
    return bad


def main():
    bad = 0
    for t in (test_pin_with_a_slot_is_established,
              test_pin_without_a_slot_is_reported_not_dropped,
              test_region_bound_still_wins_over_a_duplicate_pin):
        print(f"--- {t.__name__}")
        bad += t()
    if bad:
        print(f"\n{bad} check(s) FAILED")
        return 1
    print("\nall checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
